In [ ]:
# import pandas and assign it to the variable 'pd'
import pandas as pd

# we often import NumPy numerical python with pandas
import numpy as np

#load matplotlib for plotting later in the workshop
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# import csv
unemployment = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/country_total.csv')

In [ ]:
# type unemployment
type(unemployment)

pandas.DataFrame

In [ ]:
# read the 5 rows
unemployment.head()

  country seasonality    month  unemployment  unemployment_rate
0      at         nsa  1993.01        171000                4.5
1      at         nsa  1993.02        175000                4.6
2      at         nsa  1993.03        166000                4.4
3      at         nsa  1993.04        157000                4.1
4      at         nsa  1993.05        147000                3.9

In [ ]:
# Read the size of the DataFrame
unemployment.shape

(20796, 5)

In [ ]:
# Read the total columns of csv
unemployment.columns

Index(['country', 'seasonality', 'month', 'unemployment', 'unemployment_rate'], dtype='str')

In [ ]:
# Read the type data of columns
unemployment.dtypes

country                  str
seasonality              str
month                float64
unemployment           int64
unemployment_rate    float64
dtype: object

In [ ]:
# Describe the summary about the table
unemployment.describe()

              month  unemployment  unemployment_rate
count  20796.000000  2.079600e+04       19851.000000
mean    1999.401290  7.900818e+05           8.179764
std        7.483751  1.015280e+06           3.922533
min     1983.010000  2.000000e+03           1.100000
25%     1994.090000  1.400000e+05           5.200000
50%     2001.010000  3.100000e+05           7.600000
75%     2006.010000  1.262250e+06          10.000000
max     2010.120000  4.773000e+06          20.900000