In [ ]:
# import pandas and assign it to the variable 'pd'
import pandas as pd

# we often import NumPy numerical python with pandas
import numpy as np

#load matplotlib for plotting later in the workshop
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# import csv
unemployment = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/country_total.csv')

In [ ]:
# type unemployment
type(unemployment)

pandas.DataFrame

In [ ]:
# read the 5 rows
unemployment.head()

  country seasonality    month  unemployment  unemployment_rate
0      at         nsa  1993.01        171000                4.5
1      at         nsa  1993.02        175000                4.6
2      at         nsa  1993.03        166000                4.4
3      at         nsa  1993.04        157000                4.1
4      at         nsa  1993.05        147000                3.9

In [ ]:
# Read the size of the DataFrame
unemployment.shape

(20796, 5)

In [ ]:
# Read the total columns of csv
unemployment.columns

Index(['country', 'seasonality', 'month', 'unemployment', 'unemployment_rate'], dtype='str')

In [ ]:
# Read the type data of columns
unemployment.dtypes

country                  str
seasonality              str
month                float64
unemployment           int64
unemployment_rate    float64
dtype: object

In [ ]:
# Describe the summary about the table
unemployment.describe()

              month  unemployment  unemployment_rate
count  20796.000000  2.079600e+04       19851.000000
mean    1999.401290  7.900818e+05           8.179764
std        7.483751  1.015280e+06           3.922533
min     1983.010000  2.000000e+03           1.100000
25%     1994.090000  1.400000e+05           5.200000
50%     2001.010000  3.100000e+05           7.600000
75%     2006.010000  1.262250e+06          10.000000
max     2010.120000  4.773000e+06          20.900000

In [17]:
my_list = ['a', 'b', 'c', 'd', 'e', 'f']

In [ ]:
#Print the last 4 items
my_list[2:]

['c', 'd', 'e', 'f']

In [19]:
my_list[len(my_list)-4:]

['c', 'd', 'e', 'f']

In [5]:
import pandas as pd
country = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/countries.csv')

In [22]:
country.describe()

        latitude  longitude
count  30.000000  30.000000
mean   49.092609  14.324579
std     7.956624  11.257010
min    35.129141  -8.239122
25%    43.230916   6.979186
50%    49.238087  14.941462
75%    54.090400  23.351690
max    64.950159  35.439795

In [25]:
country.columns

Index(['country', 'google_country_code', 'country_group', 'name_en', 'name_fr',
       'name_de', 'latitude', 'longitude'],
      dtype='str')

In [6]:
country.shape

(30, 8)

In [23]:
country.dtypes

country                    str
google_country_code        str
country_group              str
name_en                    str
name_fr                    str
name_de                    str
latitude               float64
longitude              float64
dtype: object

In [7]:
country.info

<bound method DataFrame.info of    country google_country_code country_group  \
0       at                  AT            eu
1       be                  BE            eu
2       bg                  BG            eu
3       hr                  HR        non-eu
4       cy                  CY            eu
5       cz                  CZ            eu
6       dk                  DK            eu
7       ee                  EE            eu
8       fi                  FI            eu
9       fr                  FR            eu
10      de                  DE            eu
11      gr                  GR            eu
12      hu                  HU            eu
13      ie                  IE            eu
14      it                  IT            eu
15      lv                  LV            eu
16      lt                  LT            eu
17      lu                  LU            eu
18      mt                  MT            eu
19      nl                  NL            eu
20      no                  NO        non-eu
21      pl                  PL            eu
22      pt                  PT            eu
23      ro                  RO            eu
24      sk                  SK            eu
25      si                  SI            eu
26      es                  ES            eu
27      se                  SE            eu
28      tr                  TR        non-eu
29      uk                  GB            eu

                                      name_en  \
0                                     Austria
1                                     Belgium
2                                    Bulgaria
3                                     Croatia
4                                      Cyprus
5                              Czech Republic
6                                     Denmark
7                                     Estonia
8                                     Finland
9                                      France
10  Germany (including  former GDR from 1991)
11                                     Greece
12                                    Hungary
13                                    Ireland
14                                      Italy
15                                     Latvia
16                                  Lithuania
17                                 Luxembourg
18                                      Malta
19                                Netherlands
20                                     Norway
21                                     Poland
22                                   Portugal
23                                    Romania
24                                   Slovakia
25                                   Slovenia
26                                      Spain
27                                     Sweden
28                                     Turkey
29                             United Kingdom

                                              name_fr  \
0                                            Autriche
1                                            Belgique
2                                            Bulgarie
3                                             Croatie
4                                              Chypre
5                                  République tchèque
6                                            Danemark
7                                             Estonie
8                                            Finlande
9                                              France
10  Allemagne (incluant l'ancienne RDA à partir de...
11                                              Grèce
12                                            Hongrie
13                                            Irlande
14                                             Italie
15                                           Lettonie
16                                           Lituanie
17                                         Luxembourg
18                                              Malte
19                                           Pays-Bas
20                                            Norvège
21                                            Pologne
22                                           Portugal
23                                           Roumanie
24                                          Slovaquie
25                                           Slovénie
26                                            Espagne
27                                              Suède
28                                            Turquie
29                                        Royaume-Uni

                                              name_de   latitude  longitude
0                                          Österreich  47.696554  13.345980
1                                             Belgien  50.501045   4.476674
2                                           Bulgarien  42.725674  25.482322
3                                            Kroatien  44.746643  15.340844
4                                              Zypern  35.129141  33.428682
5                               Tschechische Republik  49.803531  15.474998
6                                            Dänemark  55.939684   9.516689
7                                             Estland  58.592469  25.806950
8                                            Finnland  64.950159  26.067564
9                                          Frankreich  46.710994   1.718561
10  Deutschland (einschließlich der ehemaligen DDR...  51.163825  10.454048
11                                       Griechenland  39.698467  21.577256
12                                             Ungarn  47.161163  19.504265
13                                             Irland  53.415260  -8.239122
14                                            Italien  42.504191  12.573787
15                                           Lettland  56.880117  24.606555
16                                            Litauen  55.173687  23.943168
17                                          Luxemburg  49.815319   6.133352
18                                              Malta  35.902422  14.447461
19                                        Niederlande  52.108118   5.330198
20                                           Norwegen  64.556460  12.665766
21                                              Polen  51.918907  19.134334
22                                           Portugal  39.558069  -7.844941
23                                           Rumänien  45.942611  24.990152
24                                           Slowakei  48.672644  19.700032
25                                          Slowenien  46.149259  14.986617
26                                            Spanien  39.895013  -2.988296
27                                           Schweden  62.198467  14.896307
28                                             Türkei  38.952942  35.439795
29                             Vereinigtes Königreich  54.315447  -2.232612  >

In [8]:
#Search by name of columns and row
country.loc[3,'country_group']

'non-eu'

In [11]:
#Search rows
country.loc[:4,:]

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
0,at,AT,eu,Austria,Autriche,Österreich,47.696554,13.345980
1,be,BE,eu,Belgium,Belgique,Belgien,50.501045,4.476674
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
3,hr,HR,non-eu,Croatia,Croatie,Kroatien,44.746643,15.340844
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682

In [12]:
#Search all rows but 
country.iloc[:,:-4]

,country,google_country_code,country_group,name_en
0,at,AT,eu,Austria
1,be,BE,eu,Belgium
2,bg,BG,eu,Bulgaria
3,hr,HR,non-eu,Croatia
4,cy,CY,eu,Cyprus
5,cz,CZ,eu,Czech Republic
6,dk,DK,eu,Denmark
7,ee,EE,eu,Estonia
8,fi,FI,eu,Finland
9,fr,FR,eu,France
10,de,DE,eu,Germany (including former GDR from 1991)
11,gr,GR,eu,Greece
12,hu,HU,eu,Hungary
13,ie,IE,eu,Ireland
14,it,IT,eu,Italy
15,lv,LV,eu,Latvia
16,lt,LT,eu,Lithuania
17,lu,LU,eu,Luxembourg
18,mt,MT,eu,Malta
19,nl,NL,eu,Netherlands
20,no,NO,non-eu,Norway
21,pl,PL,eu,Poland
22,pt,PT,eu,Portugal
23,ro,RO,eu,Romania
24,sk,SK,eu,Slovakia
25,si,SI,eu,Slovenia
26,es,ES,eu,Spain
27,se,SE,eu,Sweden
28,tr,TR,non-eu,Turkey
29,uk,GB,eu,United Kingdom

In [ ]:
#Select rows from 20 until 25
test = country.loc[20:25, :]
test

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
20,no,NO,non-eu,Norway,Norvège,Norwegen,64.556460,12.665766
21,pl,PL,eu,Poland,Pologne,Polen,51.918907,19.134334
22,pt,PT,eu,Portugal,Portugal,Portugal,39.558069,-7.844941
23,ro,RO,eu,Romania,Roumanie,Rumänien,45.942611,24.990152
24,sk,SK,eu,Slovakia,Slovaquie,Slowakei,48.672644,19.700032
25,si,SI,eu,Slovenia,Slovénie,Slowenien,46.149259,14.986617

In [ ]:
#Filter the DataFrame to show only rows non-eu
test[test['country_group'] == 'non-eu']

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
20,no,NO,non-eu,Norway,Norvège,Norwegen,64.55646,12.665766

In [ ]:
#Filter the DataFrame country to whow only rows > 25
country[country['longitude']>25]

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682
7,ee,EE,eu,Estonia,Estonie,Estland,58.592469,25.806950
8,fi,FI,eu,Finland,Finlande,Finnland,64.950159,26.067564
28,tr,TR,non-eu,Turkey,Turquie,Türkei,38.952942,35.439795